#!/bin/sh

### BEGIN INIT INFO
# Provides:          aesdlcd_driver
# Required-Start:    $syslog $local_fs
# Required-Stop:     $syslog $local_fs
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Load aesdlcd_driver module
# Description:       Load aesdlcd_driver I2C module for RPi5
### END INIT INFO

MODDIR="/lib/modules/$(uname -r)/extra"

case "$1" in
start)
    echo "Loading aesdlcd_driver module"
    # aesdlcd_load expects to be run from the directory containing the .ko file
    (cd $MODDIR && /usr/bin/aesdlcd_load)
    ;;
stop)
    echo "Unloading aesdlcd_driver module"
    /usr/bin/aesdchar_unload
    ;;
*)
    echo "Usage: $0 {start|stop}"
    exit 1
    ;;
esac

exit 0