#!/bin/sh
module=aesdchar
device=aesdchar
mode="664"

# Only change directory if the module is not in the current directory
# This allows the script to be run from the directory where the module is located
# (e.g. by the init script) without forcing a change to the script directory
if [ ! -e ./${module}.ko ]; then
    if [ -e $(dirname $0)/${module}.ko ]; then
        cd $(dirname $0)
    fi
fi

set -e
# Group: since distributions do it differently, look for wheel or use staff
if grep -q '^staff:' /etc/group; then
    group="staff"
else
    group="wheel"
fi

if [ -e ${module}.ko ]; then
    echo "Loading local built file ${module}.ko"
    insmod ./$module.ko $* || exit 1
else
    echo "Local file ${module}.ko not found, attempting to modprobe"
    modprobe ${module} || exit 1
fi
major=$(awk "\$2==\"$module\" {print \$1}" /proc/devices)
rm -f /dev/${device}
mknod /dev/${device} c $major 0
chgrp $group /dev/${device}
chmod $mode  /dev/${device}
